"""empty message

Revision ID: 291352225536
Revises: 0676188283b8
Create Date: 2022-03-28 13:37:19.159393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291352225536'
down_revision = '0676188283b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', sa.String(length=64), nullable=False))
    op.create_index('idx_api_path', 'project', ['api_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'name')
    op.drop_index('idx_api_path', table_name='project')
    # ### end Alembic commands ###
